// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.21.0";

// src/lib/mcp/tools/list-topics.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.21.0";
import { elifbaTopics } from "npm:@/data/topics/elifba";
var list_topics_default = defineTool({
  name: "list_topics",
  title: "Konular\u0131 listele",
  description: "Elifb\xE2 m\xFCfredat\u0131ndaki t\xFCm konular\u0131 (10 konu: Harfler, Yaz\u0131l\u0131\u015Flar, Harekeler, Cezm, \u015Eedde, Med, \xC2sar, Tenvin, Zamir, Elif-L\xE2m) d\xF6nd\xFCr\xFCr.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const topics = elifbaTopics.map((t) => ({
      id: t.id,
      title: t.title,
      description: t.description,
      itemCount: t.items.length,
      hasVideo: Boolean(t.video)
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(topics, null, 2) }],
      structuredContent: { topics }
    };
  }
});

// src/lib/mcp/tools/get-topic.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.21.0";
import { z } from "npm:zod@^3.25.76";
import { elifbaTopics as elifbaTopics2 } from "npm:@/data/topics/elifba";
var get_topic_default = defineTool2({
  name: "get_topic",
  title: "Konu detay\u0131",
  description: "Bir Elifb\xE2 konusunun t\xFCm \xF6\u011Felerini (harf/hece/kelime, Arap\xE7a glif, T\xFCrk\xE7e okunu\u015F, ses dosyas\u0131 yolu, b\xF6l\xFCm) d\xF6nd\xFCr\xFCr.",
  inputSchema: {
    topicId: z.string().describe("Konu id (\xF6r. 'harfler', 'harekeler', 'cezm', 'sedde', 'med', 'tenvin').")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ topicId }) => {
    const topic = elifbaTopics2.find((t) => t.id === topicId);
    if (!topic) {
      const known = elifbaTopics2.map((t) => t.id).join(", ");
      return {
        content: [
          { type: "text", text: `Konu bulunamad\u0131: ${topicId}. Mevcut konular: ${known}` }
        ],
        isError: true
      };
    }
    const payload = {
      id: topic.id,
      title: topic.title,
      description: topic.description,
      video: topic.video ?? null,
      items: topic.items.map((it) => ({
        id: it.id,
        label: it.label,
        arabic: it.emoji ?? null,
        speech: it.speech,
        translit: it.translit ?? null,
        audio: it.audio ?? null,
        section: it.section ?? null
      }))
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/get-letter.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.21.0";
import { z as z2 } from "npm:zod@^3.25.76";
import { elifbaTopics as elifbaTopics3 } from "npm:@/data/topics/elifba";
var get_letter_default = defineTool3({
  name: "get_letter",
  title: "Harf bilgisi",
  description: "28 temel Arap harfinden birini T\xFCrk\xE7e ad\u0131 (Elif, Be, Cim, Vev, Ye...) veya Arap\xE7a glifi ile arar; okunu\u015F ve ses dosyas\u0131 yolunu d\xF6nd\xFCr\xFCr.",
  inputSchema: {
    query: z2.string().describe("Harf ad\u0131 (T\xFCrk\xE7e) veya Arap\xE7a glif. \xD6r: 'Elif', '\u0628', 'Cim'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ query }) => {
    const letters = elifbaTopics3.find((t) => t.id === "harfler")?.items ?? [];
    const q = query.trim().toLocaleLowerCase("tr");
    const match = letters.find(
      (l) => l.label.toLocaleLowerCase("tr") === q || l.translit?.toLocaleLowerCase("tr") === q || l.emoji === query.trim()
    );
    if (!match) {
      return {
        content: [{ type: "text", text: `Harf bulunamad\u0131: ${query}` }],
        isError: true
      };
    }
    const payload = {
      name: match.label,
      arabic: match.emoji ?? null,
      speech: match.speech,
      audio: match.audio ?? null
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "elifmim-mcp",
  title: "Elifmim MCP",
  version: "0.1.0",
  instructions: "Elifmim (Elifb\xE2 \xF6\u011Frenme uygulamas\u0131) i\xE7in ortak m\xFCfredat ara\xE7lar\u0131. Kur'an Arap alfabesindeki 28 harfi, harekeleri, cezm/\u015Fedde/med/tenvin konular\u0131n\u0131 ve her \xF6\u011Fenin Arap\xE7a glifi, T\xFCrk\xE7e okunu\u015Fu ile hoca ses kayd\u0131 yolunu d\xF6nd\xFCr\xFCr. Herkese a\xE7\u0131k \xF6\u011Fretici veridir.",
  tools: [list_topics_default, get_topic_default, get_letter_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.21.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
