// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.21.0";

// src/lib/mcp/tools/list-topics.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.21.0";

// src/data/topics/elifba.ts
var LETTERS = [
  { n: 1, name: "Elif", iso: "\u0627", init: "\u0627", med: "\u0640\u0627", fin: "\u0640\u0627", speech: "elif", cons: "", thick: "ince" },
  { n: 2, name: "Be", iso: "\u0628", init: "\uFE91", med: "\uFE92", fin: "\uFE90", speech: "be", cons: "b", thick: "ince" },
  { n: 3, name: "Te", iso: "\u062A", init: "\uFE97", med: "\uFE98", fin: "\uFE96", speech: "te", cons: "t", thick: "ince" },
  { n: 4, name: "Se", iso: "\u062B", init: "\uFE9B", med: "\uFE9C", fin: "\uFE9A", speech: "se", cons: "s", thick: "ince" },
  { n: 5, name: "Cim", iso: "\u062C", init: "\uFE9F", med: "\uFEA0", fin: "\uFE9E", speech: "cim", cons: "c", thick: "ince" },
  { n: 6, name: "Ha", iso: "\u062D", init: "\uFEA3", med: "\uFEA4", fin: "\uFEA2", speech: "ha", cons: "h", thick: "ra" },
  { n: 7, name: "H\u0131", iso: "\u062E", init: "\uFEA7", med: "\uFEA8", fin: "\uFEA6", speech: "h\u0131", cons: "h", thick: "kalin" },
  { n: 8, name: "Dal", iso: "\u062F", init: "\u062F", med: "\u0640\u062F", fin: "\u0640\u062F", speech: "dal", cons: "d", thick: "ince" },
  { n: 9, name: "Zel", iso: "\u0630", init: "\u0630", med: "\u0640\u0630", fin: "\u0640\u0630", speech: "zel", cons: "z", thick: "ince" },
  { n: 10, name: "Ra", iso: "\u0631", init: "\u0631", med: "\u0640\u0631", fin: "\u0640\u0631", speech: "ra", cons: "r", thick: "ra" },
  { n: 11, name: "Ze", iso: "\u0632", init: "\u0632", med: "\u0640\u0632", fin: "\u0640\u0632", speech: "ze", cons: "z", thick: "ince" },
  { n: 12, name: "Sin", iso: "\u0633", init: "\uFEB3", med: "\uFEB4", fin: "\uFEB2", speech: "sin", cons: "s", thick: "ince" },
  { n: 13, name: "\u015Ein", iso: "\u0634", init: "\uFEB7", med: "\uFEB8", fin: "\uFEB6", speech: "\u015Fin", cons: "\u015F", thick: "ince" },
  { n: 14, name: "Sad", iso: "\u0635", init: "\uFEBB", med: "\uFEBC", fin: "\uFEBA", speech: "sad", cons: "s", thick: "kalin" },
  { n: 15, name: "Dad", iso: "\u0636", init: "\uFEBF", med: "\uFEC0", fin: "\uFEBE", speech: "dad", cons: "d", thick: "kalin" },
  { n: 16, name: "Ta", iso: "\u0637", init: "\uFEC3", med: "\uFEC4", fin: "\uFEC2", speech: "ta", cons: "t", thick: "kalin" },
  { n: 17, name: "Za", iso: "\u0638", init: "\uFEC7", med: "\uFEC8", fin: "\uFEC6", speech: "za", cons: "z", thick: "kalin" },
  { n: 18, name: "Ayn", iso: "\u0639", init: "\uFECB", med: "\uFECC", fin: "\uFECA", speech: "ayn", cons: "", thick: "ra" },
  { n: 19, name: "\u011Eayn", iso: "\u063A", init: "\uFECF", med: "\uFED0", fin: "\uFECE", speech: "gay\u0131n", cons: "g", thick: "kalin" },
  { n: 20, name: "Fe", iso: "\u0641", init: "\uFED3", med: "\uFED4", fin: "\uFED2", speech: "fe", cons: "f", thick: "ince" },
  { n: 21, name: "Gaf", iso: "\u0642", init: "\uFED7", med: "\uFED8", fin: "\uFED6", speech: "kaf", cons: "k", thick: "kalin" },
  { n: 22, name: "Kef", iso: "\u0643", init: "\uFEDB", med: "\uFEDC", fin: "\uFEDA", speech: "kef", cons: "k", thick: "ince" },
  { n: 23, name: "Lem", iso: "\u0644", init: "\uFEDF", med: "\uFEE0", fin: "\uFEDE", speech: "lem", cons: "l", thick: "ince" },
  { n: 24, name: "Mim", iso: "\u0645", init: "\uFEE3", med: "\uFEE4", fin: "\uFEE2", speech: "mim", cons: "m", thick: "ince" },
  { n: 25, name: "Nun", iso: "\u0646", init: "\uFEE7", med: "\uFEE8", fin: "\uFEE6", speech: "nun", cons: "n", thick: "ince" },
  { n: 26, name: "Vev", iso: "\u0648", init: "\u0648", med: "\u0640\u0648", fin: "\u0640\u0648", speech: "vev", cons: "v", thick: "ince" },
  { n: 27, name: "He", iso: "\u0647", init: "\uFEEB", med: "\uFEEC", fin: "\uFEEA", speech: "he", cons: "h", thick: "ince" },
  { n: 28, name: "Ye", iso: "\u064A", init: "\uFEF3", med: "\uFEF4", fin: "\uFEF2", speech: "ye", cons: "y", thick: "ince" }
];
function harekeVowels(thick) {
  if (thick === "kalin") return { a: "a", i: "\u0131", u: "u" };
  if (thick === "ra") return { a: "a", i: "i", u: "u" };
  return { a: "e", i: "i", u: "\xFC" };
}
var pad2 = (n) => n < 10 ? `0${n}` : String(n);
var audioPath = (name) => `/audio/elifba/${name}`;
var byName = new Map(LETTERS.map((l) => [l.name, l]));
var bolum = (n) => `${Math.floor((n - 1) / 4) + 1}. B\xF6l\xFCm`;
var YAZILIS_SECTIONS = [
  [1, 22, 23],
  // ا ك ل — dikey çizgililer
  [2, 3, 4],
  // ب ت ث — diş + nokta
  [5, 6, 7],
  // ج ح خ — çanaklılar
  [8, 9],
  // د ذ
  [10, 11],
  // ر ز
  [12, 13],
  // س ش
  [14, 15],
  // ص ض
  [16, 17],
  // ط ظ
  [18, 19],
  // ع غ
  [20, 21],
  // ف ق
  [24, 27],
  // م ه — ilmekliler
  [25, 28],
  // ن ي — diş ailesinin devamı
  [26]
  // و
];
var YAZILIS_SECTION_OF = /* @__PURE__ */ new Map();
YAZILIS_SECTIONS.forEach((letters, i) => {
  for (const n of letters) YAZILIS_SECTION_OF.set(n, `${i + 1}. B\xF6l\xFCm`);
});
var bolumYazilis = (n) => YAZILIS_SECTION_OF.get(n) ?? "Ekstralar";
var P = "elifba";
var t1_harfler = {
  id: "harfler",
  parent: P,
  title: "1. Harfler",
  description: "28 temel Arap harfi",
  emoji: "\uFE8D",
  practiceMode: "visual",
  gridCols: 4,
  items: LETTERS.map((l) => ({
    id: `l1-${pad2(l.n)}`,
    label: l.name,
    speech: l.speech,
    lang: "tr",
    emoji: l.iso,
    translit: l.name,
    audio: audioPath(`basic-${pad2(l.n)}.mp3`),
    section: bolum(l.n)
  }))
};
var t2_yazilislar = {
  id: "yazilislar",
  parent: P,
  title: "2. Harflerin Yaz\u0131l\u0131\u015Flar\u0131",
  description: "Ba\u015Fta, ortada ve sonda halleri",
  emoji: "\uFE91",
  practiceMode: "visual",
  gridCols: 3,
  // YENİ MÜFREDAT (kullanıcı kararı): bu konu ALIŞTIRMASIZ — çocuk videoyu
  // izler ya da harfleri birkaç dakika dinler ve geçer. Başta/ortada/sonda
  // hâlleri tek başına ezberletilmez; sıradaki konuda HAREKEYLE BİRLİKTE
  // alıştırması yapılır (şe → şın ortada + fetha). Tek başına 84 şekil
  // ezberletmek hem sıkıcı hem de okumaya doğrudan katkısı yok.
  noPractice: true,
  items: LETTERS.flatMap((l) => [
    {
      id: `l2-${pad2(l.n)}-init`,
      label: `${l.name} \u2022 ba\u015Fta`,
      speech: l.speech,
      lang: "tr",
      emoji: l.init,
      translit: `${l.name} (ba\u015Fta)`,
      audio: audioPath(`basic-${pad2(l.n)}.mp3`),
      section: bolumYazilis(l.n)
    },
    {
      id: `l2-${pad2(l.n)}-med`,
      label: `${l.name} \u2022 ortada`,
      speech: l.speech,
      lang: "tr",
      emoji: l.med,
      translit: `${l.name} (ortada)`,
      audio: audioPath(`basic-${pad2(l.n)}.mp3`),
      section: bolumYazilis(l.n)
    },
    {
      id: `l2-${pad2(l.n)}-fin`,
      label: `${l.name} \u2022 sonda`,
      speech: l.speech,
      lang: "tr",
      emoji: l.fin,
      translit: `${l.name} (sonda)`,
      audio: audioPath(`basic-${pad2(l.n)}.mp3`),
      section: bolumYazilis(l.n)
    }
  ])
};
var HAREKE = [
  { suf: "fetha", mark: "\u064E", vowel: "a" },
  // ــَ  → "e/a"
  { suf: "esre", mark: "\u0650", vowel: "i" },
  // __ِ  → "i/ı"
  { suf: "otre", mark: "\u064F", vowel: "u" }
  // ــُ  → "ü/u"
];
var HAREKE_ALISTIRMA_KELIMELERI = [
  // sayfa 10
  [["Dad", "a"], ["Ra", "a"], ["Be", "a"]],
  // ضَرَبَ
  [["Gaf", "a"], ["Ra", "a"], ["Elif", "a"]],
  // قَرَاَ
  [["Ra", "a"], ["Cim", "a"], ["Ayn", "a"]],
  // رَجَعَ
  [["Ra", "a"], ["Ze", "a"], ["Gaf", "a"]],
  // رَزَقَ
  [["Sad", "a"], ["Be", "a"], ["Ra", "a"]],
  // صَبَرَ
  [["Ra", "a"], ["Fe", "a"], ["Ayn", "a"]],
  // رَفَعَ
  [["Ye", "a"], ["Dal", "a"], ["Kef", "a"]],
  // يَدَكَ
  [["Za", "a"], ["He", "a"], ["Ra", "a"]],
  // ظَهَرَ
  [["Ha", "a"], ["Mim", "i"], ["Dal", "a"]],
  // حَمِدَ
  [["Sin", "a"], ["Mim", "i"], ["Ayn", "a"]],
  // سَمِعَ
  [["Ayn", "a"], ["Mim", "i"], ["Lem", "a"]],
  // عَمِلَ
  [["Sad", "a"], ["Ayn", "i"], ["Gaf", "a"]],
  // صَعِقَ
  [["Sad", "a"], ["Ayn", "i"], ["Dal", "a"]],
  // صَعِدَ
  [["Ta", "a"], ["Fe", "i"], ["Gaf", "a"]],
  // طَفِقَ
  [["Nun", "a"], ["Dad", "i"], ["Cim", "a"]],
  // نَضِجَ
  [["Fe", "a"], ["Ra", "i"], ["Ha", "a"]],
  // فَرِحَ
  [["Se", "u"], ["Lem", "u"], ["Se", "u"]],
  // ثُلُثُ
  [["Kef", "u"], ["Te", "u"], ["Be", "u"]],
  // كُتُبُ
  [["H\u0131", "u"], ["Lem", "u"], ["Gaf", "u"]],
  // خُلُقُ
  [["Ra", "u"], ["Sin", "u"], ["Lem", "u"]],
  // رُسُلُ
  [["Sad", "a"], ["Mim", "a"], ["Dal", "u"]],
  // صَمَدُ
  [["Fe", "a"], ["He", "u"], ["Vev", "a"]],
  // فَهُوَ
  [["Gaf", "u"], ["Te", "i"], ["Lem", "a"]],
  // قُتِلَ
  [["Ra", "a"], ["\u011Eayn", "i"], ["Be", "a"]],
  // رَغِبَ
  [["Mim", "a"], ["Ra", "i"], ["Dad", "a"]],
  // مَرِضَ
  [["\u011Eayn", "u"], ["Fe", "i"], ["Ra", "a"]],
  // غُفِرَ
  [["Zel", "u"], ["Kef", "i"], ["Ra", "a"]],
  // ذُكِرَ
  // sayfa 11
  [["\u015Ein", "a"], ["Cim", "a"], ["Ra", "a"]],
  // شَجَرَ
  [["Sin", "u"], ["Be", "u"], ["Lem", "a"]],
  // سُبُلَ
  [["Kef", "a"], ["Zel", "i"], ["Be", "a"]],
  // كَذِبَ
  [["H\u0131", "a"], ["Ta", "i"], ["Ra", "a"]],
  // خَطِرَ
  [["Te", "a"], ["Be", "i"], ["Ayn", "a"]],
  // تَبِعَ
  [["Kef", "a"], ["Sin", "a"], ["Be", "a"]],
  // كَسَبَ
  [["Ta", "u"], ["Be", "i"], ["Ayn", "a"]],
  // طُبِعَ
  [["Ra", "a"], ["Kef", "i"], ["Be", "a"]],
  // رَكِبَ
  [["Ha", "a"], ["Sin", "u"], ["Nun", "a"]],
  // حَسُنَ
  [["Lem", "a"], ["Ayn", "i"], ["Be", "a"]],
  // لَعِبَ
  [["Sad", "a"], ["Dal", "a"], ["Gaf", "a"]],
  // صَدَقَ
  [["Ayn", "u"], ["Nun", "u"], ["Gaf", "u"]],
  // عُنُقُ
  [["Vev", "a"], ["Sad", "a"], ["Fe", "a"]],
  // وَصَفَ
  [["Vev", "a"], ["Sin", "i"], ["Ayn", "a"]],
  // وَسِعَ
  [["Dal", "a"], ["H\u0131", "a"], ["Lem", "a"]],
  // دَخَلَ
  [["Sin", "a"], ["Ra", "i"], ["Ayn", "a"]],
  // سَرِعَ
  [["Nun", "a"], ["Kef", "a"], ["Sad", "a"]],
  // نَكَصَ
  [["Fe", "a"], ["Ze", "i"], ["Ayn", "a"]],
  // فَزِعَ
  [["Ra", "u"], ["Ze", "i"], ["Gaf", "a"]],
  // رُزِقَ
  [["Be", "a"], ["Ra", "a"], ["Ze", "a"]],
  // بَرَزَ
  [["Ra", "u"], ["Be", "u"], ["Ayn", "u"]],
  // رُبُعُ
  [["Kef", "a"], ["Ra", "i"], ["He", "a"]],
  // كَرِهَ
  [["Lem", "a"], ["Ayn", "a"], ["Nun", "a"]],
  // لَعَنَ
  [["Ha", "a"], ["Sin", "i"], ["Be", "a"]],
  // حَسِبَ
  [["Be", "a"], ["Ta", "a"], ["Nun", "a"]],
  // بَطَنَ
  [["Sin", "a"], ["H\u0131", "i"], ["Ra", "a"]],
  // سَخِرَ
  [["Ra", "a"], ["He", "i"], ["Gaf", "a"]]
  // رَهِقَ
];
var NON_CONNECT = /* @__PURE__ */ new Set(["Elif", "Dal", "Zel", "Ra", "Ze", "Vev"]);
var HV_TO_SUF = { a: "fetha", i: "esre", u: "otre" };
var HV_MARK = { a: "\u064E", i: "\u0650", u: "\u064F" };
function buildHarekeExtras() {
  const seen = /* @__PURE__ */ new Set();
  const out = [];
  for (const word of HAREKE_ALISTIRMA_KELIMELERI) {
    for (let i = 0; i < word.length; i++) {
      const [name, hv] = word[i];
      const l = byName.get(name);
      if (!l) continue;
      const prevConnects = i > 0 && !NON_CONNECT.has(word[i - 1][0]);
      const hasNext = i < word.length - 1;
      const pos = !prevConnects && hasNext ? "init" : prevConnects && hasNext ? "med" : prevConnects ? "fin" : "iso";
      if (pos === "iso") continue;
      const form = pos === "init" ? l.init : pos === "med" ? l.med : l.fin;
      if (form === l.iso) continue;
      const key = `${l.n}|${form}|${hv}`;
      if (seen.has(key)) continue;
      seen.add(key);
      const v = harekeVowels(l.thick);
      const read = `${l.cons}${v[hv]}`;
      const posTr = pos === "init" ? "ba\u015Fta" : pos === "med" ? "ortada" : "sonda";
      const suf = HV_TO_SUF[hv];
      const harekeAd = suf === "fetha" ? "fethal\u0131" : suf === "esre" ? "esreli" : "\xF6treli";
      out.push({
        id: `l3x-${pad2(l.n)}-${pos}-${hv}`,
        label: `${l.name} ${posTr} ${harekeAd}`,
        speech: read,
        lang: "tr",
        emoji: form + HV_MARK[hv],
        translit: read,
        audio: audioPath(`hareke-${pad2(l.n)}-${suf}.mp3`),
        section: bolum(l.n),
        // ÖLÇÜLEN: harekeyi bildiği varsayılır, hata harfin ŞEKLİNE
        // yazılır. 2. konuda (Yazılışlar) alıştırmasız geçilen
        // başta/ortada/sonda hâlleri asıl burada ölçülür.
        skill: `l2-${pad2(l.n)}-${pos}`,
        // Şıklar AYNI HAREKELİ olmalı: ölçülen harfin şekli,
        // harekeler karışsaydı çocuk sesteki ünlüden eler, şekle bakmazdı.
        distractorKey: `hv-${hv}`,
        // Bu soru harekeyi BİLDİĞİNİ varsayar. Hareke L4 değilse yanlış
        // cevap şekle değil HAREKEYE yazılır (yanlış teşhis olmasın).
        prereqSkill: `hrk-${suf}`
      });
    }
  }
  return out;
}
var t3_harekeler = {
  id: "harekeler",
  parent: P,
  title: "3. Harekeler",
  // Şıklar aynı harfin üç harekesi (بَ بِ بُ) — dördüncü şık başka harf
  // olurdu ve çocuk harekeye bakmadan elerdi.
  optionCount: 3,
  description: "Fetha, esre ve \xF6tre",
  emoji: "\uFE77",
  practiceMode: "visual",
  gridCols: 3,
  items: [
    ...LETTERS.flatMap(
      (l) => HAREKE.map((h) => {
        const v = harekeVowels(l.thick);
        const sesMap = {
          a: `${l.cons}${v.a}`,
          i: `${l.cons}${v.i}`,
          u: `${l.cons}${v.u}`
        };
        return {
          id: `l3-${pad2(l.n)}-${h.suf}`,
          label: `${l.name} ${h.suf}`,
          speech: sesMap[h.vowel],
          lang: "tr",
          emoji: l.iso + h.mark,
          translit: sesMap[h.vowel],
          audio: audioPath(`hareke-${pad2(l.n)}-${h.suf}.mp3`),
          section: bolum(l.n),
          // ÖLÇÜLEN: harf değil HAREKE. 84 hece sorulur ama yeni bilgi 3
          // tanedir (28 harf 1. konuda öğrenildi). Çocuk üstün/esre/ötreyi
          // ayırt edebiliyorsa konu biter — bkz. src/lib/skills.ts.
          skill: `hrk-${h.suf}`,
          // Şıklar AYNI HARF olmalı (بَ بِ بُ): ölçülen hareke,
          // farklı harf koyulsaydı çocuk harften tanır, harekeye bakmazdı.
          distractorKey: `harf-${pad2(l.n)}`
        };
      })
    )
  ]
};
var OGRETME_ORNEKLEMI = /* @__PURE__ */ new Set([2, 10, 12, 24]);
var CEKIRDEK_AGIRLIK = 3;
var ekstraAgirlik = (frekans) => CEKIRDEK_AGIRLIK + frekans * 2;
var t4_harf_hareke = {
  id: "harf-hareke",
  parent: P,
  title: "4. Harf + Hareke Al\u0131\u015Ft\u0131rmas\u0131",
  description: "Harflerin ba\u015Fta/ortada/sonda h\xE2lleri, harekeyle",
  emoji: "\uFEB7\u064E",
  practiceMode: "visual",
  gridCols: 3,
  items: buildHarekeExtras()
};
var CEZM_MISSING = /* @__PURE__ */ new Set();
var CEZM_EKSTRA = [
  ["\u0647\u064F\u0645\u0652", "h\xFCm", 3],
  // 2.577
  ["\u0645\u0650\u0646\u0652", "min", 3],
  // 2.281
  ["\u0644\u064E\u064A\u0652", "ley", 3],
  // 1.224
  ["\u0647\u0650\u0645\u0652", "him", 3],
  //   919
  ["\u0645\u064E\u0646\u0652", "men", 3],
  //   837
  ["\u0628\u0650\u0644\u0652", "bil", 3],
  //   585 — harf-i tarif okuyuşu (bi + el → bil)
  ["\u0642\u064E\u0648\u0652", "kav", 3],
  //   509
  ["\u064A\u064E\u0639\u0652", "ye'", 3],
  //   403
  ["\u0642\u064E\u062F\u0652", "kad", 2],
  //   398
  ["\u0644\u064E\u0645\u0652", "lem", 2],
  //   385
  ["\u0642\u064F\u0644\u0652", "kul", 2],
  //   350
  ["\u0643\u064F\u0646\u0652", "k\xFCn", 2],
  //   329
  ["\u0642\u064E\u0628\u0652", "kab", 2],
  //   248
  ["\u064A\u064E\u0633\u0652", "yes", 2]
  //   237
];
var t4_cezm = {
  id: "cezm",
  parent: P,
  title: "5. Cezm",
  description: "Cezimli okuyu\u015F (eb, ib, \xFCb\u2026)",
  emoji: "\uFE7F",
  practiceMode: "visual",
  gridCols: 3,
  items: [
    ...LETTERS.filter((l) => l.n >= 2).flatMap((l) => {
      const cezmIdx = l.n - 1;
      const hasAudio = !CEZM_MISSING.has(l.n);
      const base = l.cons || (l.n === 18 ? "'" : "");
      const v = harekeVowels(l.thick);
      return [
        { v: "e", audio: `cezm-${pad2(cezmIdx)}-e.mp3`, sp: `${v.a}${base}` },
        { v: "i", audio: `cezm-${pad2(cezmIdx)}-i.mp3`, sp: `${v.i}${base}` },
        { v: "u", audio: `cezm-${pad2(cezmIdx)}-u.mp3`, sp: `${v.u}${base}` }
      ].map((h, idx) => {
        const elifPre = idx === 0 ? "\u0627\u064E" : idx === 1 ? "\u0627\u0650" : "\u0627\u064F";
        return {
          id: `l4-${pad2(l.n)}-${h.v}`,
          label: `${h.sp}`,
          speech: h.sp,
          lang: "tr",
          // Örn: اَبْ / اِبْ / اُبْ
          emoji: `${elifPre}${l.iso}\u0652`,
          translit: h.sp,
          audio: hasAudio ? audioPath(h.audio) : void 0,
          section: bolum(l.n)
        };
      });
    }),
    ...CEZM_EKSTRA.map(([ar, sp, w], i) => ({
      id: `l4e-${pad2(i + 1)}`,
      audio: `/audio/elifba/cezm-ekstra-${pad2(i + 1)}.mp3`,
      label: sp,
      speech: sp.replace(/'/g, ""),
      lang: "tr",
      emoji: ar,
      translit: sp,
      section: "Ekstralar",
      weight: ekstraAgirlik(w)
    }))
  ]
};
var SEDDE_EKSTRA = [
  ["\u0627\u0650\u0646\u064E\u0651", "inne", 3],
  // 1.513 — Kur'an'ın en sık şeddeli hecesi
  ["\u0627\u0650\u0644\u064E\u0651", "ille", 3],
  //   665
  ["\u0631\u064E\u0628\u0650\u0651", "rabbi", 3],
  //   609
  ["\u0627\u064E\u0646\u064E\u0651", "enne", 3],
  //   408
  ["\u062B\u064F\u0645\u064E\u0651", "s\xFCmme", 2],
  //   338
  ["\u0631\u064E\u0628\u064E\u0651", "rabbe", 2],
  //   210
  ["\u0643\u064F\u0644\u0650\u0651", "k\xFClli", 2],
  //   192
  ["\u0627\u064E\u064A\u064F\u0651", "eyy\xFC", 2],
  //   172
  ["\u0631\u064E\u0628\u064F\u0651", "rabb\xFC", 2],
  //   171
  ["\u0644\u064E\u0645\u064E\u0651", "lemme", 2],
  //   165
  ["\u0645\u0650\u0645\u064E\u0651", "mimme", 2],
  //   159
  ["\u0639\u064E\u0644\u064E\u0651", "alle", 2],
  //   153
  ["\u0627\u0650\u0646\u0650\u0651", "inni", 2],
  //   151
  ["\u062D\u064E\u062A\u064E\u0651", "hatte", 1]
  //   142
];
var SEDDE_ELIF_PRE = {
  fetha: "\u0627\u064E",
  esre: "\u0627\u0650",
  otre: "\u0627\u064F"
};
var t5_sedde = {
  id: "sedde",
  parent: P,
  title: "6. \u015Eedde",
  description: "\u015Eeddeli okuyu\u015F (ebbe, ibbe, \xFCbbe\u2026)",
  emoji: "\uFE7D",
  practiceMode: "visual",
  gridCols: 3,
  items: [
    ...LETTERS.filter((l) => l.n >= 2).flatMap((l) => {
      const idx = l.n - 1;
      const base = l.cons || (l.n === 18 ? "'" : "");
      const ikile = (x) => base === "'" ? `${x}${base}` : `${x}${base}${base}`;
      const v = harekeVowels(l.thick);
      return HAREKE.map((h) => {
        const sesMap = {
          a: `${ikile(v.a)}${v.a}`,
          i: `${ikile(v.i)}${v.a}`,
          u: `${ikile(v.u)}${v.a}`
        };
        return {
          id: `l5-${pad2(l.n)}-${h.suf}`,
          label: sesMap[h.vowel],
          speech: sesMap[h.vowel],
          lang: "tr",
          // Şeddeli hece TEK BAŞINA okunamaz: "بَّ" yazıp "ebbe" demek
          // olmuyor, şeddenin ikizlediği ilk sessizin bir önceki heceye
          // yaslanması gerekiyor. Cezm konusunda olduğu gibi harekeli elif
          // ön eki konur → اَبَّ / اِبَّ / اُبَّ (ebbe / ibbe / übbe).
          // Ekstra kartlar (اِنَّ, رَبِّ…) da zaten bu biçimde.
          // ⚠️ NFC ile normalize: Unicode'un kanonik sırası HAREKEYİ şeddeden
          // ÖNCE ister ve Diyanet metni de öyle kodlanmış (الضَّٓالّٖينَ =
          // ض + fetha + şedde). Biz şeddeyi önce yazıyorduk; ekranda ikisi
          // PİKSEL PİKSEL aynı çiziliyor (ölçüldü) ama dizgiler eşit
          // olmadığı için karşılaştırma/arama sessizce tutmuyordu.
          emoji: `${SEDDE_ELIF_PRE[h.suf]}${l.iso}\u064E\u0651`.normalize("NFC"),
          translit: sesMap[h.vowel],
          audio: audioPath(`sedde-${pad2(idx)}-${h.suf}.mp3`),
          section: bolum(l.n),
          // Yalnız öğretme örneklemi sorulur; gerisi görülür/dinlenir.
          practice: OGRETME_ORNEKLEMI.has(l.n)
        };
      });
    }),
    ...SEDDE_EKSTRA.map(([ar, sp, w], i) => ({
      id: `l5e-${pad2(i + 1)}`,
      audio: `/audio/elifba/sedde-ekstra-${pad2(i + 1)}.mp3`,
      label: sp,
      speech: sp,
      lang: "tr",
      emoji: ar,
      translit: sp,
      section: "Ekstralar",
      weight: ekstraAgirlik(w)
    }))
  ]
};
var MED_EKSTRA = [
  ["\u0644\u064E\u0627", "l\xE2", 3],
  // 4.019
  ["\u0645\u064E\u0627", "m\xE2", 3],
  // 3.890
  ["\u0646\u064E\u0627", "n\xE2", 3],
  // 3.351
  ["\u0648\u064E\u0627", "v\xE2", 3],
  // 2.641
  ["\u0627\u0670", "\xE2", 3],
  // 2.244 — medli elif (Türk imlâsı: elif + hançer elif)
  ["\u0647\u064E\u0627", "h\xE2", 3],
  // 1.956
  ["\u0641\u0656\u064A", "f\xEE", 3],
  // 1.794
  ["\u0644\u064F\u0648", "l\xFB", 3],
  // 1.563
  ["\u0630\u0656\u064A", "z\xEE", 3],
  // 1.470
  ["\u0647\u064F\u0648", "h\xFB", 3],
  // 1.338
  ["\u064A\u064E\u0627", "y\xE2", 3],
  // 1.185
  ["\u0631\u064F\u0648", "r\xFB", 3],
  // 1.184
  ["\u0646\u064F\u0648", "n\xFB", 3],
  // 1.097
  ["\u0647\u0656\u064A", "h\xEE", 3]
  // 1.091
];
var byIso = new Map(LETTERS.map((l) => [l.iso, l]));
var MED_FORMS = [
  // ⚠️ UZUN "â" VE "û" MUSHAFTA ZATEN NORMAL HAREKEYLE YAZILIR — كَالَ değil
  // مَالِكِ · اَعُوذُ · يُولَدْ · صُدُورِ. Yani بَا ve بُو mushaf yazımıdır,
  // değişmedi.
  { suf: "fetha", mark: "\u064E", harf: "\u0627" },
  // ⚠️ AMA UZUN "î" FARKLI: mushafta med yâsının önündeki esre KÜÇÜK yazılır
  // ve yâ noktalı kalır → بٖي. Kaynak Diyanet metni: الرَّحٖيمِ · فٖي ·
  // اَلَّذٖي · الْعَالَمٖينَ · قَدٖيرٌ. (Kullanıcı şartı: ders tabloları da
  // Diyanet/Hayrat mushafına göre.) Noktasız "ى" ise YALNIZ kelime sonunda
  // ve "â" okunurken kullanılır — وَتَعَالٰى.
  { suf: "esre", mark: "\u0656", harf: "\u064A" },
  { suf: "otre", mark: "\u064F", harf: "\u0648" }
];
function medVowel(thick, suf) {
  if (suf === "esre") return "\xEE";
  if (suf === "otre") return "\xFB";
  return thick === "ince" ? "\xEA" : "\xE2";
}
var t6_med = {
  id: "med",
  parent: P,
  title: "7. Med Harfleri",
  description: "Elif, vav ve ye ile uzatma",
  // Rozet de Türk imlâsında: "ﺁ" (madda'lı bitişik biçim) yerine اٰ.
  emoji: "\u0627\u0670",
  practiceMode: "visual",
  gridCols: 3,
  items: [
    ...LETTERS.flatMap(
      (l) => MED_FORMS.map((m) => {
        const sp = `${l.cons}${medVowel(l.thick, m.suf)}`;
        const ar = l.n === 1 && m.suf === "fetha" ? "\u0627\u0670" : l.iso + m.mark + m.harf;
        return {
          id: `l6-${pad2(l.n)}-${m.suf}`,
          label: sp,
          speech: sp,
          lang: "tr",
          emoji: ar,
          translit: sp,
          audio: audioPath(`med-${pad2(l.n)}-${m.suf}.mp3`),
          section: bolum(l.n),
          // Yalnız öğretme örneklemi sorulur; gerisi görülür/dinlenir.
          practice: OGRETME_ORNEKLEMI.has(l.n)
        };
      })
    ),
    ...MED_EKSTRA.map(([ar, sp, w], i) => ({
      id: `l6e-${pad2(i + 1)}`,
      label: sp,
      speech: sp,
      lang: "tr",
      emoji: ar,
      translit: sp,
      audio: `/audio/elifba/med-ekstra-${pad2(i + 1)}.mp3`,
      section: "Ekstralar",
      weight: ekstraAgirlik(w)
    }))
  ]
};
var ASAR = [
  ["\u0627\u0670\u0645\u064E\u0646\u064E", "\xE2mene"],
  // 2:285 — medd-i bedel (اٰ)
  ["\u0645\u064E\u0627\u0644\u0650\u0643\u0650", "m\xE2liki"],
  // 1:4  — medd-i tabiî
  ["\u064A\u064F\u0631\u064E\u0653\u0627\u0624\u064F\u06DF\u0646\u064E", "y\xFCr\xE2\xFBne"],
  // 4:142 — medd-i muttasıl
  ["\u0627\u064F\u0648\u06DF\u0644\u0670\u0653\u0626\u0650\u0643\u064E", "ul\xE2ike"],
  // 2:5  — medd-i muttasıl
  // ⚠️ KART TEK BAŞINA DURUYOR: mushafta bu kelime cümle içinde geçtiği için
  // vasl elifi harekesiz (`قَالَ الْمَلَأُ`), ama kart bir başlangıçtır —
  // başlangıçta "ال" harekelidir (bkz. `اَلْحَمْدُ لِلّٰهِ`, `اَلشَّمْسُ`).
  // Harekesiz elifle başlayan kart çocuğa "bu harf sessiz" demez, hiçbir şey
  // demez (kullanıcı tespiti: "harekesiz harf gördün mü mushafta").
  ["\u0627\u064E\u0644\u0652\u0645\u064E\u0644\u064E\u0623\u064F", "el-mele'\xFC"],
  // 7:60 — kelime SONU hemze çizilir; MED YOK (kasr)
  ["\u0627\u0670\u0628\u064E\u0653\u0627\u0624\u064F\u06DF\u0646\u064E\u0627", "\xE2b\xE2un\xE2"],
  // 7:70 — medd-i bedel + muttasıl
  ["\u0627\u064E\u0644\u0636\u064E\u0651\u0653\u0627\u0644\u0651\u0656\u064A\u0646\u064E", "d\xE2ll\xEEn"],
  // 1:7  — medd-i lâzım (6 hareke); kart başı "ال" harekeli
  ["\u062D\u064E\u0653\u0627\u062C\u064F\u0651\u0648\u0643\u064E", "h\xE2cc\xFBke"]
  // 3:20 — medd-i lâzım + şedde
];
var t7_asar = {
  id: "asar-med-kasr",
  parent: P,
  title: "8. \xC2sar, Med ve Kasr",
  description: "Uzatma i\u015Faretleri \u2014 videoyu izle",
  // Rozet, konunun kendi konusu olan MED İŞARETİNİ gösterir (مَٓا).
  emoji: "\u0645\u064E\u0653\u0627",
  practiceMode: "visual",
  gridCols: 2,
  noPractice: true,
  video: "https://www.youtube.com/watch?v=s6oYG1Bl77E",
  items: ASAR.map(([ar, sp], i) => ({
    id: `l7-${pad2(i + 1)}`,
    label: sp,
    speech: sp,
    lang: "tr",
    emoji: ar,
    translit: sp,
    audio: `/audio/elifba/asar-${pad2(i + 1)}.mp3`
  }))
};
var TENVIN_EKSTRA = [
  ["\u0628\u064E\u062F\u064B\u0627", "beden"],
  ["\u0628\u064E\u0629\u064B", "beten"],
  ["\u0646\u064E\u0629\u064B", "neten"],
  ["\u0646\u064E\u0629\u064C", "net\xFCn"],
  ["\u064A\u064E\u0629\u064C", "yet\xFCn"],
  ["\u0642\u064E\u0629\u064D", "katin"],
  ["\u0644\u064E\u0629\u064C", "let\xFCn"],
  ["\u062F\u064E\u0629\u064C", "det\xFCn"]
];
var t8_tenvin = {
  id: "tenvin",
  parent: P,
  title: "9. Tenvin",
  description: "\u0130ki \xFCst\xFCn, iki esre, iki \xF6tre",
  emoji: "\u08F0",
  practiceMode: "visual",
  gridCols: 3,
  items: [
    ...LETTERS.flatMap((l) => {
      const v = harekeVowels(l.thick);
      const defs = [
        // iki üstün: harf + fethatan + elif (بًا) — elif kendisi yalnız "اً"
        { suf: "ustun2", file: "fetha", glyph: l.n === 1 ? "\u0627\u064B" : `${l.iso}\u064B\u0627`, read: `${l.cons}${v.a}n` },
        { suf: "esre2", file: "esre", glyph: `${l.iso}\u064D`, read: `${l.cons}${v.i}n` },
        { suf: "otre2", file: "otre", glyph: `${l.iso}\u064C`, read: `${l.cons}${v.u}n` }
      ];
      return defs.map((d) => ({
        id: `l8-${pad2(l.n)}-${d.suf}`,
        label: d.read,
        speech: d.read,
        lang: "tr",
        emoji: d.glyph,
        translit: d.read,
        audio: audioPath(`tenvin-${pad2(l.n)}-${d.file}.mp3`),
        section: bolum(l.n),
        // Yalnız öğretme örneklemi sorulur; gerisi görülür/dinlenir.
        practice: OGRETME_ORNEKLEMI.has(l.n)
      }));
    }),
    ...TENVIN_EKSTRA.map(([ar, sp], i) => ({
      id: `l8x-${pad2(i + 1)}`,
      audio: `/audio/elifba/tenvin-ekstra-${pad2(i + 1)}.mp3`,
      label: sp,
      speech: sp,
      lang: "tr",
      emoji: ar,
      translit: sp,
      section: "Ekstralar",
      // Ekstralar L4'te bile diğer L4 öğelerden daha sık sorulsun.
      weight: ekstraAgirlik(3)
    }))
  ]
};
var t9_zamir = {
  id: "zamir-lafzatullah",
  parent: P,
  title: "10. Zamir ve Lafzatullah",
  description: "Allah lafz\u0131n\u0131n okunu\u015Fu",
  // Rozet de mushaf yazımında: "ﷲ" bitişik biçimi hançer elifi göstermiyor.
  emoji: "\u0627\u0644\u0644\u0651\u0670\u0647",
  practiceMode: "visual",
  gridCols: 2,
  noPractice: true,
  video: "https://www.youtube.com/watch?v=btL_AHHnbaE",
  items: [
    { ar: "\u0627\u064E\u0644\u0644\u0651\u0670\u0647\u064F", sp: "All\xE2h" },
    { ar: "\u0628\u0650\u0627\u0644\u0644\u0651\u0670\u0647\u0650", sp: "bill\xE2hi" },
    { ar: "\u0645\u064E\u0639\u064E \u0627\u0644\u0644\u0651\u0670\u0647\u0650", sp: "meall\xE2hi" },
    { ar: "\u0642\u064F\u0644\u0650 \u0627\u0644\u0644\u0651\u0670\u0647\u064F\u0645\u064E\u0651", sp: "kulill\xE2h\xFCmme" },
    { ar: "\u0641\u064E\u0627\u0650\u0646\u064E\u0651 \u0627\u0644\u0644\u0651\u0670\u0647\u064E", sp: "feinnall\xE2he" },
    // ⚠️ ZAMİR HÂ'SININ İKİ YAZIMI AYRI: ötreli zamir mushafta SADE yazılır
    // (`لَهُ` — Araf 70 "وَحْدَهُ", İhlâs 4 "لَهُ"), ama esreli zamir UZUN
    // okunduğu için küçük esre alır: `هٖ` (Bakara 285 "مِنْ رَبِّهٖ ·
    // وَمَلٰٓئِكَتِهٖ · وَكُتُبِهٖ"). Düz `بِهِ` yazımı "bihi" diye KISA okutur,
    // oysa kartın okunuşu "bihî".
    { ar: "\u0644\u064E\u0647\u064F", sp: "leh\xFB" },
    { ar: "\u0644\u064E\u0647\u064F\u0645\u0652", sp: "leh\xFCm" },
    { ar: "\u0628\u0650\u0647\u0656", sp: "bih\xEE" }
  ].map((it, i) => ({
    id: `l9-${pad2(i + 1)}`,
    audio: `/audio/elifba/zamir-${pad2(i + 1)}.mp3`,
    label: it.sp,
    speech: it.sp,
    lang: "tr",
    emoji: it.ar,
    translit: it.sp
  }))
};
var t10_elif_lam = {
  id: "elif-lam-ra",
  parent: P,
  title: "11. Elif-L\xE2m Tak\u0131s\u0131 ve R\xE2",
  description: "\u0627\u0644 tak\u0131s\u0131 ve r\xE2 harfinin okunu\u015Fu",
  emoji: "\uFE8D\uFEDF",
  practiceMode: "visual",
  gridCols: 2,
  noPractice: true,
  video: "https://www.youtube.com/watch?v=kZ4R2CrWc3A",
  items: [
    { ar: "\u0627\u064E\u0644\u0652\u0628\u064E\u064A\u0652\u062A\u064F", sp: "el-beyt\xFC" },
    { ar: "\u0627\u064E\u0644\u0634\u064E\u0651\u0645\u0652\u0633\u064F", sp: "e\u015F-\u015Fems\xFC" },
    { ar: "\u0627\u064E\u0644\u0631\u064E\u0651\u062D\u0652\u0645\u0670\u0646\u064F", sp: "er-Rahm\xE2n" },
    { ar: "\u0627\u064E\u0644\u0652\u062D\u064E\u0645\u0652\u062F\u064F", sp: "el-hamd\xFC" },
    { ar: "\u0648\u064E\u064A\u064E\u0633\u0650\u0651\u0631\u0652 \u0644\u0656\u064A", sp: "ve yessir l\xEE" },
    // Tâhâ 26 — mushafta لٖي
    { ar: "\u0641\u064E\u0637\u064E\u0647\u0650\u0651\u0631\u0652", sp: "fetahhir" },
    { ar: "\u0648\u064E\u0627\u0633\u0652\u062A\u064E\u063A\u0652\u0641\u0650\u0631\u0652\u0647\u064F", sp: "vesta\u011Ffirh\xFC" },
    { ar: "\u0631\u064E\u0628\u0650\u0651", sp: "Rabbi" }
  ].map((it, i) => ({
    id: `l10-${pad2(i + 1)}`,
    audio: `/audio/elifba/eliflam-${pad2(i + 1)}.mp3`,
    label: it.sp,
    speech: it.sp,
    lang: "tr",
    emoji: it.ar,
    translit: it.sp
  }))
};
var t2b_yazilis_hafiza = {
  id: "yazilis-hafiza",
  parent: P,
  title: "Yaz\u0131l\u0131\u015F Haf\u0131za Y\xF6ntemi",
  description: "84 \u015Fekli ezberleme \u2014 \xFC\xE7 kural\u0131 \xF6\u011Fren",
  emoji: "\u0640\u0628\u0640",
  practiceMode: "visual",
  noPractice: true,
  page: "/yazilis-hafiza",
  items: []
};
var elifbaTopics = [
  t1_harfler,
  t2_yazilislar,
  t2b_yazilis_hafiza,
  t3_harekeler,
  t4_harf_hareke,
  t4_cezm,
  t5_sedde,
  t6_med,
  t7_asar,
  t8_tenvin,
  t9_zamir,
  t10_elif_lam
];

// src/lib/mcp/tools/list-topics.ts
var list_topics_default = defineTool({
  name: "list_topics",
  title: "Konular\u0131 listele",
  description: "Elifb\xE2 m\xFCfredat\u0131ndaki t\xFCm konular\u0131 (10 konu: Harfler, Yaz\u0131l\u0131\u015Flar, Harekeler, Cezm, \u015Eedde, Med, \xC2sar, Tenvin, Zamir, Elif-L\xE2m) d\xF6nd\xFCr\xFCr.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const topics = elifbaTopics.map((t) => ({
      id: t.id,
      title: t.title,
      description: t.description,
      itemCount: t.items.length,
      hasVideo: Boolean(t.video)
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(topics, null, 2) }],
      structuredContent: { topics }
    };
  }
});

// src/lib/mcp/tools/get-topic.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.21.0";
import { z } from "npm:zod@^3.25.76";
var get_topic_default = defineTool2({
  name: "get_topic",
  title: "Konu detay\u0131",
  description: "Bir Elifb\xE2 konusunun t\xFCm \xF6\u011Felerini (harf/hece/kelime, Arap\xE7a glif, T\xFCrk\xE7e okunu\u015F, ses dosyas\u0131 yolu, b\xF6l\xFCm) d\xF6nd\xFCr\xFCr.",
  inputSchema: {
    topicId: z.string().describe("Konu id (\xF6r. 'harfler', 'harekeler', 'cezm', 'sedde', 'med', 'tenvin').")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ topicId }) => {
    const topic = elifbaTopics.find((t) => t.id === topicId);
    if (!topic) {
      const known = elifbaTopics.map((t) => t.id).join(", ");
      return {
        content: [
          { type: "text", text: `Konu bulunamad\u0131: ${topicId}. Mevcut konular: ${known}` }
        ],
        isError: true
      };
    }
    const payload = {
      id: topic.id,
      title: topic.title,
      description: topic.description,
      video: topic.video ?? null,
      items: topic.items.map((it) => ({
        id: it.id,
        label: it.label,
        arabic: it.emoji ?? null,
        speech: it.speech,
        translit: it.translit ?? null,
        audio: it.audio ?? null,
        section: it.section ?? null
      }))
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/get-letter.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.21.0";
import { z as z2 } from "npm:zod@^3.25.76";
var get_letter_default = defineTool3({
  name: "get_letter",
  title: "Harf bilgisi",
  description: "28 temel Arap harfinden birini T\xFCrk\xE7e ad\u0131 (Elif, Be, Cim, Vev, Ye...) veya Arap\xE7a glifi ile arar; okunu\u015F ve ses dosyas\u0131 yolunu d\xF6nd\xFCr\xFCr.",
  inputSchema: {
    query: z2.string().describe("Harf ad\u0131 (T\xFCrk\xE7e) veya Arap\xE7a glif. \xD6r: 'Elif', '\u0628', 'Cim'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ query }) => {
    const letters = elifbaTopics.find((t) => t.id === "harfler")?.items ?? [];
    const q = query.trim().toLocaleLowerCase("tr");
    const match = letters.find(
      (l) => l.label.toLocaleLowerCase("tr") === q || l.translit?.toLocaleLowerCase("tr") === q || l.emoji === query.trim()
    );
    if (!match) {
      return {
        content: [{ type: "text", text: `Harf bulunamad\u0131: ${query}` }],
        isError: true
      };
    }
    const payload = {
      name: match.label,
      arabic: match.emoji ?? null,
      speech: match.speech,
      audio: match.audio ?? null
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "elifmim-mcp",
  title: "Elifmim MCP",
  version: "0.1.0",
  instructions: "Elifmim (Elifb\xE2 \xF6\u011Frenme uygulamas\u0131) i\xE7in ortak m\xFCfredat ara\xE7lar\u0131. Kur'an Arap alfabesindeki 28 harfi, harekeleri, cezm/\u015Fedde/med/tenvin konular\u0131n\u0131 ve her \xF6\u011Fenin Arap\xE7a glifi, T\xFCrk\xE7e okunu\u015Fu ile hoca ses kayd\u0131 yolunu d\xF6nd\xFCr\xFCr. Herkese a\xE7\u0131k \xF6\u011Fretici veridir.",
  tools: [list_topics_default, get_topic_default, get_letter_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.21.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
